version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  lint:
    executor:
      name: python/default
      tag: 3.10.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linters
          command: make lint
  unit-tests:
    executor:
      name: python/default
      tag: 3.10.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
  datahub-ingest:
    executor:
      name: python/default
      tag: 3.10.10
    parameters:
      recipe:
        type: string
        description: Repository path to the source recipe
      before-ingest:
        type: steps
        description: Steps to be executed directly before the datahub-ingest command
        default: []
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - steps: << parameters.before-ingest >>
      - run:
          name: Sync Datahub source
          command: |
            export DATAHUB_GMS_URL="https://mozilla.acryl.io/gms"
            python -m datahub ingest -c << parameters.recipe >>

workflows:
  ci:
    jobs:
      - lint
      - unit-tests:
          requires:
            - lint
  nightly:  # Sync custom integration sources
    jobs:
      - unit-tests
      - datahub-ingest:
          name: glean-source
          recipe: recipes/glean_recipe.dhub.yaml
          requires:
            - unit-tests
      - datahub-ingest:
          name: legacytelemetry-source
          recipe: recipes/legacy_recipe.dhub.yaml
          requires:
            - unit-tests
      - datahub-ingest:
          name: metrichub-glossary-source
          recipe: recipes/metrichub_recipe.dhub.yaml
          before-ingest:
            - run:
                name: Generate Metric-Hub Glossary YAML
                command: python -m sync.datahub.metrichub_glossary
            - run:
                name: Connect Glossary Terms to Tables
                command: python -m datahub dataset upsert -f datasets.yaml
          requires:
            - unit-tests
      - datahub-ingest:
          name: bigquery-etl-source
          recipe: recipes/bigquery_etl_recipe.dhub.yaml
          requires:
            - unit-tests
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
