version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  unit-tests:
    executor:
      name: python/default
      tag: 3.10.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
  glean-source:
    executor:
      name: python/default
      tag: 3.10.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - &set_env 
        run:
          name: "Set environment variables"
          command: echo 'export DATAHUB_GMS_URL="https://mozilla.acryl.io/gms"' >> "$BASH_ENV"
      - run:
          name: Sync Glean Pings
          command: datahub ingest -c recipes/glean_recipe.dhub.yaml
  legacytelemetry-source:
    executor:
      name: python/default
      tag: 3.10.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - *set_env
      - run:
          name: Sync Legacy Telemetry Pings
          command: datahub ingest -c recipes/legacy_recipe.dhub.yaml

workflows:
  ci:
    jobs:
      - unit-tests
  nightly:  # Sync custom integration sources
    jobs:
      - unit-tests
      - glean-source:
          requires:
            - unit-tests
      - legacytelemetry-source:
          requires:
            - unit-tests
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
